name: taskmanager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.6

  # Cache Image From Network
  cached_network_image: ^3.3.1

  # Responsive UI
  sizer: ^2.0.15

  # Flutter Offline
  flutter_offline: ^3.0.1

  # Flutter SVG
  flutter_svg: ^2.0.10+1

  # API Call Services
  dio: ^5.4.3+1

  # Auto Singleton Package
  get_it: ^7.7.0

  # No-Sql Database
  hive: ^2.2.3

  # Navigator Router
  go_router: ^14.1.1

  # State Management UI&Logic
  provider: ^6.1.2

  # Json Handler
  json_annotation: ^4.8.1

  # Auto Generate Call APIs Function Depended On Dio
  retrofit: ^4.1.0

  # Lunch URLs
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: ^4.6.0
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:

  uses-material-design: true

  fonts:
    - family: medium
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
    - family: inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
    - family: text
      fonts:
        - asset: assets/fonts/TextMeOne-Regular.ttf
